// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { Injectable } from "@nestjs/common";
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
@Injectable()
export class PrismaService extends PrismaClient {
    todo: any;
    constructor() {
        const adapter = new PrismaPg({
            connectionString: process.env.DATABASE_URL as string,
        });
        super({ adapter });
    }
}
